[profile.default]
src = "contracts"
out = "out" 
libs = ["contracts/lib"]
solc = "0.8.24"
optimizer = false0
via_ir = true

# 依赖配置
remappings = [
    "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=contracts/lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=contracts/lib/forge-std/src/"
]
title = "ETF System Documentation"